name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build for ${{ matrix.build.name }}
    runs-on: ${{ matrix.build.os }}
    container: debian:11
    strategy:
      fail-fast: false
      matrix:
        build:
          - {os: ubuntu-24.04, variant: debian, name: Debian, artifact: debian-x64}
          - {os: ubuntu-24.04-arm, variant: debian, name: Debian ARM, artifact: debian-arm}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Toolchain
        run: ./scripts/setup-debian.sh ${{ matrix.build.variant }}
        if: runner.os == 'Linux'

      - name: Build for ${{ matrix.build.name }}
        run: ./scripts/build-ci.sh ${{ matrix.build.variant }}

      - name: Get short SHA
        run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      - name: Upload ${{ matrix.build.name }} to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpac-${{ env.SHA7 }}-${{ matrix.build.artifact }}
          path: ${{ github.workspace }}/build/*.*

  release:
    name: Release
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          pattern: '*'
      - name: Run SHA1SUM
        id: checksum
        run: |
          echo 'sha1sum<<EOF' >> $GITHUB_OUTPUT
          sha1sum * >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            ```plain
            ${{ steps.checksum.outputs.sha1sum }}
            ```
          append_body: true
          files: '*'
